### ISSUE TITLE
Getting values from a BINTABLE

### ISSUE THREAD

**Issue by todlandis** [brampf/fitscore#12]
I'm gettting compile time errors at the starred lines using FITSKit to see a BINTABLE:
                   
         if let tableHDU = hdus[i] as? AnyTableHDU<BFIELD> {
                                for i in 0..<tableHDU.tfields! {
                                    print("\(i) - \(tableHDU.columns[i].TTYPE!)")
                                    print("\(i) - \(tableHDU.columns[i].TUNIT!)")
                                    print("\(i) - \(tableHDU.columns[i].TFORM!)")
                                }
                                print(tableHDU.columns[1][2])        ***
                                print(tableHDU.rows[1][2])              ***
                                tableHDU.rows.forEach { row in
                                    var  out = ""
                                        for col in 0..<row.values.count{
                                            let field:BFIELD = row.values[1] 
                                            out.append(col.format(row.TDISP(col)) ?? "N/A")).        ***
                                        }
                                        print(out)
                                }
                            }
Any idea what's going on?  Thanks for any info ...
- Tod

**Comment by brampf** [comment]
this actually is an issue in brampf/fitscore rather than brampf/fitskit and teaches me a valuable lesson:
-> always write your sample code in another module to figure not provide sample code which does not

I just changed the visibility of those functions in the brampf/fitscore/tree/fitskit-advanced branch
